-- One-time Supabase migration after lobby-rounds-and-waiting.sql,
-- security-hardening.sql, and room-guards.sql have been reapplied from this commit.
begin;
create table if not exists public.luminaria_deck_catalog (
 deck_id text not null check (deck_id in ('moonlit-archive','pop-culture')),
 card_id text not null check (card_id ~ '^[0-9]{3}-(card|pop)\.webp$'), primary key(deck_id,card_id));
insert into public.luminaria_deck_catalog(deck_id,card_id) values
  ('moonlit-archive','001-card.webp'),
  ('moonlit-archive','002-card.webp'),
  ('moonlit-archive','003-card.webp'),
  ('moonlit-archive','004-card.webp'),
  ('moonlit-archive','005-card.webp'),
  ('moonlit-archive','006-card.webp'),
  ('moonlit-archive','007-card.webp'),
  ('moonlit-archive','008-card.webp'),
  ('moonlit-archive','009-card.webp'),
  ('moonlit-archive','010-card.webp'),
  ('moonlit-archive','011-card.webp'),
  ('moonlit-archive','012-card.webp'),
  ('moonlit-archive','013-card.webp'),
  ('moonlit-archive','014-card.webp'),
  ('moonlit-archive','015-card.webp'),
  ('moonlit-archive','016-card.webp'),
  ('moonlit-archive','017-card.webp'),
  ('moonlit-archive','018-card.webp'),
  ('moonlit-archive','019-card.webp'),
  ('moonlit-archive','020-card.webp'),
  ('moonlit-archive','021-card.webp'),
  ('moonlit-archive','022-card.webp'),
  ('moonlit-archive','023-card.webp'),
  ('moonlit-archive','024-card.webp'),
  ('moonlit-archive','025-card.webp'),
  ('moonlit-archive','026-card.webp'),
  ('moonlit-archive','027-card.webp'),
  ('moonlit-archive','028-card.webp'),
  ('moonlit-archive','029-card.webp'),
  ('moonlit-archive','030-card.webp'),
  ('moonlit-archive','031-card.webp'),
  ('moonlit-archive','032-card.webp'),
  ('moonlit-archive','033-card.webp'),
  ('moonlit-archive','034-card.webp'),
  ('moonlit-archive','035-card.webp'),
  ('moonlit-archive','036-card.webp'),
  ('moonlit-archive','037-card.webp'),
  ('moonlit-archive','038-card.webp'),
  ('moonlit-archive','039-card.webp'),
  ('moonlit-archive','040-card.webp'),
  ('moonlit-archive','041-card.webp'),
  ('moonlit-archive','042-card.webp'),
  ('moonlit-archive','043-card.webp'),
  ('moonlit-archive','044-card.webp'),
  ('moonlit-archive','045-card.webp'),
  ('moonlit-archive','046-card.webp'),
  ('moonlit-archive','047-card.webp'),
  ('moonlit-archive','048-card.webp'),
  ('moonlit-archive','049-card.webp'),
  ('moonlit-archive','050-card.webp'),
  ('moonlit-archive','051-card.webp'),
  ('moonlit-archive','052-card.webp'),
  ('moonlit-archive','053-card.webp'),
  ('moonlit-archive','054-card.webp'),
  ('moonlit-archive','055-card.webp'),
  ('moonlit-archive','056-card.webp'),
  ('moonlit-archive','057-card.webp'),
  ('moonlit-archive','058-card.webp'),
  ('moonlit-archive','059-card.webp'),
  ('moonlit-archive','061-card.webp'),
  ('moonlit-archive','062-card.webp'),
  ('moonlit-archive','064-card.webp'),
  ('moonlit-archive','065-card.webp'),
  ('moonlit-archive','066-card.webp'),
  ('moonlit-archive','067-card.webp'),
  ('moonlit-archive','068-card.webp'),
  ('moonlit-archive','069-card.webp'),
  ('moonlit-archive','070-card.webp'),
  ('moonlit-archive','071-card.webp'),
  ('moonlit-archive','072-card.webp'),
  ('moonlit-archive','073-card.webp'),
  ('moonlit-archive','074-card.webp'),
  ('moonlit-archive','075-card.webp'),
  ('moonlit-archive','076-card.webp'),
  ('moonlit-archive','077-card.webp'),
  ('moonlit-archive','078-card.webp'),
  ('moonlit-archive','079-card.webp'),
  ('moonlit-archive','080-card.webp'),
  ('moonlit-archive','081-card.webp'),
  ('moonlit-archive','082-card.webp'),
  ('moonlit-archive','083-card.webp'),
  ('moonlit-archive','084-card.webp'),
  ('moonlit-archive','085-card.webp'),
  ('moonlit-archive','086-card.webp'),
  ('moonlit-archive','087-card.webp'),
  ('moonlit-archive','088-card.webp'),
  ('moonlit-archive','089-card.webp'),
  ('moonlit-archive','090-card.webp'),
  ('moonlit-archive','091-card.webp'),
  ('moonlit-archive','092-card.webp'),
  ('moonlit-archive','093-card.webp'),
  ('moonlit-archive','094-card.webp'),
  ('moonlit-archive','095-card.webp'),
  ('moonlit-archive','096-card.webp'),
  ('moonlit-archive','097-card.webp'),
  ('moonlit-archive','098-card.webp'),
  ('moonlit-archive','099-card.webp'),
  ('moonlit-archive','100-card.webp'),
  ('moonlit-archive','101-card.webp'),
  ('moonlit-archive','102-card.webp'),
  ('pop-culture','201-pop.webp'),
  ('pop-culture','202-pop.webp'),
  ('pop-culture','203-pop.webp'),
  ('pop-culture','204-pop.webp'),
  ('pop-culture','205-pop.webp'),
  ('pop-culture','206-pop.webp'),
  ('pop-culture','207-pop.webp'),
  ('pop-culture','208-pop.webp'),
  ('pop-culture','209-pop.webp'),
  ('pop-culture','210-pop.webp'),
  ('pop-culture','211-pop.webp'),
  ('pop-culture','212-pop.webp'),
  ('pop-culture','213-pop.webp'),
  ('pop-culture','214-pop.webp'),
  ('pop-culture','215-pop.webp'),
  ('pop-culture','216-pop.webp'),
  ('pop-culture','217-pop.webp'),
  ('pop-culture','218-pop.webp'),
  ('pop-culture','219-pop.webp'),
  ('pop-culture','220-pop.webp'),
  ('pop-culture','221-pop.webp'),
  ('pop-culture','222-pop.webp'),
  ('pop-culture','223-pop.webp'),
  ('pop-culture','224-pop.webp'),
  ('pop-culture','225-pop.webp'),
  ('pop-culture','226-pop.webp'),
  ('pop-culture','227-pop.webp'),
  ('pop-culture','228-pop.webp'),
  ('pop-culture','229-pop.webp'),
  ('pop-culture','230-pop.webp'),
  ('pop-culture','231-pop.webp'),
  ('pop-culture','232-pop.webp'),
  ('pop-culture','233-pop.webp'),
  ('pop-culture','234-pop.webp'),
  ('pop-culture','235-pop.webp'),
  ('pop-culture','236-pop.webp'),
  ('pop-culture','237-pop.webp'),
  ('pop-culture','238-pop.webp'),
  ('pop-culture','239-pop.webp'),
  ('pop-culture','240-pop.webp'),
  ('pop-culture','241-pop.webp'),
  ('pop-culture','242-pop.webp'),
  ('pop-culture','243-pop.webp'),
  ('pop-culture','244-pop.webp'),
  ('pop-culture','245-pop.webp'),
  ('pop-culture','246-pop.webp'),
  ('pop-culture','247-pop.webp'),
  ('pop-culture','248-pop.webp'),
  ('pop-culture','249-pop.webp'),
  ('pop-culture','250-pop.webp'),
  ('pop-culture','251-pop.webp'),
  ('pop-culture','252-pop.webp'),
  ('pop-culture','253-pop.webp'),
  ('pop-culture','254-pop.webp'),
  ('pop-culture','255-pop.webp'),
  ('pop-culture','256-pop.webp'),
  ('pop-culture','257-pop.webp'),
  ('pop-culture','258-pop.webp'),
  ('pop-culture','259-pop.webp'),
  ('pop-culture','260-pop.webp'),
  ('pop-culture','261-pop.webp'),
  ('pop-culture','262-pop.webp'),
  ('pop-culture','263-pop.webp'),
  ('pop-culture','264-pop.webp'),
  ('pop-culture','265-pop.webp'),
  ('pop-culture','266-pop.webp'),
  ('pop-culture','267-pop.webp'),
  ('pop-culture','268-pop.webp'),
  ('pop-culture','269-pop.webp'),
  ('pop-culture','270-pop.webp'),
  ('pop-culture','271-pop.webp'),
  ('pop-culture','272-pop.webp'),
  ('pop-culture','273-pop.webp'),
  ('pop-culture','274-pop.webp'),
  ('pop-culture','275-pop.webp'),
  ('pop-culture','276-pop.webp'),
  ('pop-culture','277-pop.webp'),
  ('pop-culture','278-pop.webp'),
  ('pop-culture','279-pop.webp'),
  ('pop-culture','280-pop.webp'),
  ('pop-culture','281-pop.webp'),
  ('pop-culture','282-pop.webp'),
  ('pop-culture','283-pop.webp'),
  ('pop-culture','284-pop.webp'),
  ('pop-culture','285-pop.webp'),
  ('pop-culture','286-pop.webp'),
  ('pop-culture','287-pop.webp'),
  ('pop-culture','288-pop.webp'),
  ('pop-culture','289-pop.webp'),
  ('pop-culture','290-pop.webp'),
  ('pop-culture','291-pop.webp'),
  ('pop-culture','292-pop.webp'),
  ('pop-culture','293-pop.webp'),
  ('pop-culture','294-pop.webp'),
  ('pop-culture','295-pop.webp'),
  ('pop-culture','296-pop.webp'),
  ('pop-culture','297-pop.webp'),
  ('pop-culture','298-pop.webp'),
  ('pop-culture','299-pop.webp'),
  ('pop-culture','300-pop.webp'),
  ('pop-culture','401-pop.webp'),
  ('pop-culture','402-pop.webp'),
  ('pop-culture','403-pop.webp'),
  ('pop-culture','404-pop.webp'),
  ('pop-culture','405-pop.webp'),
  ('pop-culture','406-pop.webp'),
  ('pop-culture','407-pop.webp'),
  ('pop-culture','408-pop.webp'),
  ('pop-culture','409-pop.webp'),
  ('pop-culture','410-pop.webp'),
  ('pop-culture','411-pop.webp'),
  ('pop-culture','412-pop.webp'),
  ('pop-culture','413-pop.webp'),
  ('pop-culture','414-pop.webp'),
  ('pop-culture','415-pop.webp'),
  ('pop-culture','416-pop.webp'),
  ('pop-culture','417-pop.webp'),
  ('pop-culture','418-pop.webp'),
  ('pop-culture','419-pop.webp'),
  ('pop-culture','420-pop.webp'),
  ('pop-culture','421-pop.webp'),
  ('pop-culture','422-pop.webp'),
  ('pop-culture','423-pop.webp'),
  ('pop-culture','424-pop.webp'),
  ('pop-culture','425-pop.webp'),
  ('pop-culture','426-pop.webp'),
  ('pop-culture','427-pop.webp'),
  ('pop-culture','428-pop.webp'),
  ('pop-culture','429-pop.webp'),
  ('pop-culture','430-pop.webp'),
  ('pop-culture','431-pop.webp'),
  ('pop-culture','432-pop.webp'),
  ('pop-culture','433-pop.webp'),
  ('pop-culture','434-pop.webp'),
  ('pop-culture','435-pop.webp'),
  ('pop-culture','436-pop.webp'),
  ('pop-culture','437-pop.webp'),
  ('pop-culture','438-pop.webp'),
  ('pop-culture','439-pop.webp'),
  ('pop-culture','440-pop.webp'),
  ('pop-culture','441-pop.webp'),
  ('pop-culture','442-pop.webp'),
  ('pop-culture','443-pop.webp'),
  ('pop-culture','444-pop.webp'),
  ('pop-culture','445-pop.webp'),
  ('pop-culture','446-pop.webp'),
  ('pop-culture','447-pop.webp'),
  ('pop-culture','448-pop.webp'),
  ('pop-culture','449-pop.webp'),
  ('pop-culture','450-pop.webp'),
  ('pop-culture','451-pop.webp'),
  ('pop-culture','452-pop.webp'),
  ('pop-culture','453-pop.webp'),
  ('pop-culture','454-pop.webp'),
  ('pop-culture','455-pop.webp'),
  ('pop-culture','456-pop.webp'),
  ('pop-culture','457-pop.webp'),
  ('pop-culture','458-pop.webp'),
  ('pop-culture','459-pop.webp'),
  ('pop-culture','460-pop.webp'),
  ('pop-culture','461-pop.webp'),
  ('pop-culture','462-pop.webp'),
  ('pop-culture','463-pop.webp'),
  ('pop-culture','464-pop.webp'),
  ('pop-culture','465-pop.webp'),
  ('pop-culture','466-pop.webp'),
  ('pop-culture','467-pop.webp'),
  ('pop-culture','468-pop.webp'),
  ('pop-culture','469-pop.webp'),
  ('pop-culture','470-pop.webp'),
  ('pop-culture','471-pop.webp'),
  ('pop-culture','472-pop.webp'),
  ('pop-culture','473-pop.webp'),
  ('pop-culture','474-pop.webp'),
  ('pop-culture','475-pop.webp'),
  ('pop-culture','476-pop.webp'),
  ('pop-culture','477-pop.webp'),
  ('pop-culture','478-pop.webp'),
  ('pop-culture','479-pop.webp'),
  ('pop-culture','480-pop.webp'),
  ('pop-culture','481-pop.webp'),
  ('pop-culture','482-pop.webp'),
  ('pop-culture','483-pop.webp'),
  ('pop-culture','484-pop.webp'),
  ('pop-culture','485-pop.webp'),
  ('pop-culture','486-pop.webp'),
  ('pop-culture','487-pop.webp'),
  ('pop-culture','488-pop.webp'),
  ('pop-culture','489-pop.webp'),
  ('pop-culture','490-pop.webp'),
  ('pop-culture','491-pop.webp'),
  ('pop-culture','492-pop.webp'),
  ('pop-culture','493-pop.webp'),
  ('pop-culture','494-pop.webp'),
  ('pop-culture','495-pop.webp'),
  ('pop-culture','496-pop.webp'),
  ('pop-culture','497-pop.webp'),
  ('pop-culture','498-pop.webp'),
  ('pop-culture','499-pop.webp'),
  ('pop-culture','500-pop.webp'),
  ('moonlit-archive','103-card.webp'),
  ('moonlit-archive','104-card.webp'),
  ('moonlit-archive','105-card.webp'),
  ('moonlit-archive','106-card.webp'),
  ('moonlit-archive','107-card.webp'),
  ('moonlit-archive','108-card.webp'),
  ('moonlit-archive','109-card.webp'),
  ('moonlit-archive','110-card.webp'),
  ('moonlit-archive','111-card.webp'),
  ('moonlit-archive','112-card.webp')
on conflict do nothing;
alter table public.luminaria_deck_catalog enable row level security;
revoke all on public.luminaria_deck_catalog from public,anon,authenticated;
create table if not exists public.luminaria_card_rerolls (
 room_id uuid not null references public.rooms(id) on delete cascade,
 milestone_round_id uuid not null references public.rounds(id) on delete cascade,
 player_id uuid not null references auth.users(id) on delete cascade,
 returned_card_id text, received_card_id text, created_at timestamptz not null default now(),
 primary key(milestone_round_id,player_id));
alter table public.luminaria_card_rerolls enable row level security;
revoke all on public.luminaria_card_rerolls from public,anon,authenticated;
create or replace function public.luminaria_reroll_status(target_room_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid := (select auth.uid()); room_row public.rooms%rowtype; completed integer; round_limit integer; latest public.rounds%rowtype; milestone public.rounds%rowtype; reserve integer;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 select * into room_row from public.rooms where id=target_room_id;
 if room_row.id is null or not exists(select 1 from public.room_players where room_id=target_room_id and user_id=uid) then raise exception 'Room membership required'; end if;
 if room_row.status<>'playing' then return jsonb_build_object('available',false,'reason','finished'); end if;
 select count(*) into completed from public.rounds where room_id=target_room_id and phase='results';
 select coalesce(max(position),0) into round_limit from public.room_deck_cards where room_id=target_room_id;
 if completed<5 or completed>=round_limit then return jsonb_build_object('available',false,'reason','wait'); end if;
 select * into milestone from public.rounds where room_id=target_room_id and phase='results' order by created_at,id offset ((completed/5)*5-1) limit 1;
 if milestone.id is null then return jsonb_build_object('available',false,'reason','wait'); end if;
 if exists(select 1 from public.luminaria_card_rerolls where milestone_round_id=milestone.id and player_id=uid) then return jsonb_build_object('available',false,'reason','used'); end if;
 select * into latest from public.rounds where room_id=target_room_id order by created_at desc,id desc limit 1;
 if latest.phase not in ('results','submitting') or (latest.phase='submitting' and exists(select 1 from public.card_submissions where round_id=latest.id and player_id=uid)) then return jsonb_build_object('available',false,'reason','wait'); end if;
 select count(*) into reserve from public.luminaria_deck_catalog c where c.deck_id=room_row.deck_id and not exists(select 1 from public.room_deck_cards d where d.room_id=target_room_id and d.card_id=c.card_id);
 return jsonb_build_object('available',reserve>0,'reason',case when reserve=0 then 'empty_reserve' else null end,'milestone',milestone.id,'completed',completed,'reserve',reserve);
end $$;
create or replace function public.reroll_luminaria_card(target_room_id uuid,milestone_round_id uuid,chosen_card_id text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid := (select auth.uid()); room_row public.rooms%rowtype; status_data jsonb; replacement text; position_no integer; sixth_position integer; old_card text; previous_swap public.luminaria_card_rerolls%rowtype;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 select * into room_row from public.rooms where id=target_room_id for update;
 if room_row.id is null or not exists(select 1 from public.room_players where room_id=target_room_id and user_id=uid) then raise exception 'Room membership required'; end if;
 select * into previous_swap from public.luminaria_card_rerolls where milestone_round_id=reroll_luminaria_card.milestone_round_id and player_id=uid;
 if previous_swap.milestone_round_id is not null then return jsonb_build_object('ok',true,'card_id',previous_swap.received_card_id,'retried',true); end if;
 status_data:=public.luminaria_reroll_status(target_room_id);
 if not coalesce((status_data->>'available')::boolean,false) then return jsonb_build_object('ok',false,'reason',status_data->>'reason'); end if;
 if (status_data->>'milestone')::uuid<>milestone_round_id then return jsonb_build_object('ok',false,'reason','stale'); end if;
 if chosen_card_id is not null then
  select position into position_no from public.room_deck_cards where room_id=target_room_id and owner_id=uid and card_id=chosen_card_id and not is_played for update;
  select position into sixth_position from public.room_deck_cards where room_id=target_room_id and owner_id=uid and not is_played order by position offset 5 limit 1;
  if position_no is null or (sixth_position is not null and position_no>sixth_position) then return jsonb_build_object('ok',false,'reason','not_in_hand'); end if;
  select c.card_id into replacement from public.luminaria_deck_catalog c where c.deck_id=room_row.deck_id and not exists(select 1 from public.room_deck_cards d where d.room_id=target_room_id and d.card_id=c.card_id) order by random() limit 1;
  if replacement is null then return jsonb_build_object('ok',false,'reason','empty_reserve'); end if;
  old_card:=chosen_card_id;
  update public.room_deck_cards set card_id=replacement where room_id=target_room_id and owner_id=uid and card_id=chosen_card_id and not is_played;
  if not found then return jsonb_build_object('ok',false,'reason','stale'); end if;
 end if;
 insert into public.luminaria_card_rerolls(room_id,milestone_round_id,player_id,returned_card_id,received_card_id) values(target_room_id,milestone_round_id,uid,old_card,replacement);
 return jsonb_build_object('ok',true,'card_id',replacement);
end $$;
revoke all on function public.luminaria_reroll_status(uuid) from public,anon;
revoke all on function public.reroll_luminaria_card(uuid,uuid,text) from public,anon;
grant execute on function public.luminaria_reroll_status(uuid) to authenticated;
grant execute on function public.reroll_luminaria_card(uuid,uuid,text) to authenticated;
commit;

