import assert from 'node:assert/strict';
import { handleStory } from '../worker/story-service.mjs';
import { storyLanguage } from '../src/game-finale.mjs';

assert.equal(storyLanguage([{clue:'Moonlit forest'},{clue:'Sleeping dragon'}]),'en');
assert.equal(storyLanguage([{clue:'Лунный лес'},{clue:'Спящий дракон'}]),'ru');
assert.equal(storyLanguage([{clue:'Moon'},{clue:'Forest'},{clue:'Очень длинная русская ассоциация'}]),'en');
assert.equal(storyLanguage([{clue:'123 ✨'}]),'en');

const roomId='12345678-1234-1234-1234-123456789abc';
const rounds=Array.from({length:28},(_,i)=>({id:`round-${i}`,clue:`Ассоциация ${i}`,phase:'results'}));
let member=true,finished=true,aiCalls=0,providedClues,persistedStory=null,providedTokenLimit=0,providedPrompt='';
const fetcher=async(url,options={})=>{
  if(url.endsWith('/auth/v1/user'))return Response.json({id:'user'});
  if(url.includes('room_players?'))return Response.json(member?[{user_id:'user'}]:[]);
  if(url.includes('rooms?'))return Response.json([{status:finished?'finished':'playing'}]);
  if(url.includes('rounds?'))return Response.json(rounds);
  if(url.includes('luminaria_deck_state'))return Response.json([{remaining_cards:finished?0:10}]);
  if(url.includes('/finale_stories?'))return Response.json(persistedStory?.finalRoundId===rounds.at(-1).id?[{story:persistedStory.story}]:[]);
  if(url.endsWith('/rpc/publish_luminaria_finale_story')){const body=JSON.parse(options.body);assert.equal(body.expected_final_round_id,rounds.at(-1).id);if(persistedStory?.finalRoundId!==body.expected_final_round_id)persistedStory={finalRoundId:body.expected_final_round_id,story:body.generated_story};return Response.json(persistedStory.story)}
  throw Error('Unexpected URL');
};
const store=new Map();
const cache={async match(key){return store.get(key.url)?.clone()},async put(key,response){store.set(key.url,response.clone())}};
const env={AI:{async run(model,{messages,max_tokens}){aiCalls++;providedClues=JSON.parse(messages[1].content).clues;providedTokenLimit=max_tokens;providedPrompt=messages[0].content;return {response:providedClues.at(-1).startsWith('Новая')?'Новая партия началась с загадочного автобуса, который ехал сквозь сон. Пассажиры обменяли свои карты на звёзды, а в конце пути обнаружили дверь, которой прежде не было.':('Ночью наши слова сложились в карту исчезнувшего города. За последней дверью горел свет, пока звёзды рассказывали свою историю. ').repeat(10)}}}};
const config={url:'https://example.supabase.co',key:'public-key'};
const request=(auth=true)=>new Request('https://luminaria.test/api/finale-story',{method:'POST',headers:auth?{Authorization:'Bearer token'}:{},body:JSON.stringify({roomId,language:'ru'})});
assert.equal((await handleStory(request(false),env,config,{fetcher,cache})).status,401);
finished=false;assert.equal((await handleStory(request(),env,config,{fetcher,cache})).status,409);assert.equal(aiCalls,0);
finished=true;
const results=await Promise.all([handleStory(request(),env,config,{fetcher,cache}),handleStory(request(),env,config,{fetcher,cache})]);
const first=await results[0].json();assert.equal(first.clueCount,28);assert.equal(providedClues.at(-1),'Ассоциация 27');assert.equal(aiCalls,1);assert(first.story.length>400);assert(providedPrompt.includes('approximately 84 words'));assert(providedPrompt.includes('no character limit'));assert(providedTokenLimit>=672);
assert.equal((await (await handleStory(request(),env,config,{fetcher,cache})).json()).story,first.story);assert.equal(aiCalls,1);
assert.equal(persistedStory.finalRoundId,'round-27');
const oldStory=persistedStory.story;
rounds.splice(0,rounds.length,...Array.from({length:18},(_,i)=>({id:`rematch-${i}`,clue:`Новая ассоциация ${i}`,phase:'results'})));
const second=await (await handleStory(request(),env,config,{fetcher,cache})).json();
assert.equal(second.clueCount,18);assert.equal(providedClues.at(-1),'Новая ассоциация 17');
assert.notEqual(second.story,oldStory);
assert.equal(persistedStory.finalRoundId,'rematch-17');assert.equal(aiCalls,2);
assert.equal((await (await handleStory(request(),env,config,{fetcher,cache})).json()).story,second.story);
assert.equal(aiCalls,2);assert.equal(oldStory,first.story);
store.clear();const anotherClient=await handleStory(request(),env,config,{fetcher,cache});assert.equal((await anotherClient.json()).story,second.story);assert.equal(aiCalls,2);
member=false;assert.equal((await handleStory(request(),env,config,{fetcher,cache})).status,403);
member=true;store.clear();persistedStory=null;assert.equal((await handleStory(request(),{},config,{fetcher,cache})).status,503);
for(const round of rounds)round.clue='Moonlit forest';
const englishEnv={AI:{async run(model,{messages}){assert(messages[0].content.includes('in English'));return {response:'Under the moon, the forest folded its branches into a door. We stepped through and found the stars asleep among the roots, each dreaming of a different world.'}}}};
const englishResult=await handleStory(request(),englishEnv,config,{fetcher,cache});
assert.equal(englishResult.status,200);
assert((await englishResult.json()).story.startsWith('Under the moon'));
console.log('PASS: story authorization, adaptive uncapped length, all clues sent, canonical cross-client story, shared cache, concurrency and fallback handling.');
